import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WalletProvider } from "./components/WalletContext";
import WalletNav from "./components/WalletNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProvider>
          <nav className="w-full flex items-center justify-between px-6 py-4 border-b bg-background sticky top-0 z-40">
            <div className="font-bold text-xl">Satsuma</div>
            <WalletNav />
          </nav>
          {children}
        </WalletProvider>
      </body>
    </html>
  );
}
