[package]
name = "satsuma_injective_yield_vault"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.5.0"
cw2 = "1.1.1"
cw-storage-plus = "1.1.0"
serde = { version = "1.0", features = ["derive"] } 